_wandb:
    value:
        cli_version: 0.24.0
        e:
            us9t53l2200w0132z4shy0e3cp39wbnf:
                codePath: algovirginia/workspace/DeepfakeDetectionRenewed/demo.ipynb
                cpu_count: 30
                cpu_count_logical: 30
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "532608356352"
                        used: "26118459392"
                email: yashaspatil@gmail.com
                executable: /lambda/nfs/algovirginia/workspace/DeepfakeDetectionRenewed/venv/bin/python
                git:
                    commit: e98366503f2e8a9461a0ff5b37ba536b40839ba7
                    remote: https://github.com/Katluver44/DeepfakeDetectionRenewed.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-989fb9d5-35f6-2e6e-d1bc-764bd589bd7e
                host: 150-136-33-106
                memory:
                    total: "232205717504"
                os: Linux-6.8.0-1040-nvidia-x86_64-with-glibc2.35
                program: algovirginia/workspace/DeepfakeDetectionRenewed/demo.ipynb
                python: CPython 3.10.12
                root: /lambda/nfs/algovirginia/workspace/DeepfakeDetectionRenewed
                startedAt: "2026-02-13T03:37:19.729670Z"
                writerId: us9t53l2200w0132z4shy0e3cp39wbnf
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
            "3":
                - 2
                - 16
            "4": 3.10.12
            "5": 0.24.0
            "6": 4.36.2
            "8":
                - 1
            "12": 0.24.0
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: dummy
epochs:
    value: 10
learning_rate:
    value: 0.02
test_run:
    value: true
