_wandb:
    value:
        cli_version: 0.24.0
        e:
            fhjlzuvo1t4zhg7ztrr4gpa2pyblxxk7:
                codePath: algovirginia/workspace/DeepfakeDetectionRenewed/mixed (1).ipynb
                cpu_count: 240
                cpu_count_logical: 240
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "20812690710528"
                        used: "26585378816"
                email: yashaspatil@gmail.com
                executable: /lambda/nfs/algovirginia/workspace/DeepfakeDetectionRenewed/venv/bin/python
                git:
                    commit: a0bf7702f3eab1c16c6498c10fa28ce4cce3fd66
                    remote: https://github.com/Katluver44/DeepfakeDetectionRenewed.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-89fdc1e1-18b2-f499-c12b-82bcb9bfb3fa
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-250d0a77-defa-e7c2-f82a-627c7e1333e8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-9de7367b-d49a-4703-6bda-35bcbeed8690
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-199eaf67-cda9-3e5c-5e12-9d6301374b1a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-c62c987b-706f-c6b2-6a46-bb09d6cfbc69
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-4d1d0321-2d84-f51a-1529-ddb890e51a1e
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-725e4326-96a0-430b-6f5e-a72519bb025a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-50adf40c-bb56-f580-0912-6a29a037cb2d
                host: 193-122-155-232
                memory:
                    total: "1902324826112"
                os: Linux-6.8.0-1046-nvidia-x86_64-with-glibc2.35
                program: algovirginia/workspace/DeepfakeDetectionRenewed/mixed (1).ipynb
                python: CPython 3.10.12
                root: .
                startedAt: "2026-03-19T22:02:48.014250Z"
                writerId: fhjlzuvo1t4zhg7ztrr4gpa2pyblxxk7
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 103
            "3":
                - 2
                - 7
                - 13
                - 15
                - 66
            "4": 3.10.12
            "5": 0.24.0
            "6": 4.36.2
            "8":
                - 1
            "12": 0.24.0
            "13": linux-x86_64
args:
    value: null
balance:
    value: 50/50 bonafide/spoof
batch_size:
    value: 20
cfg:
    value: Namespace(PhonemeGAT=Namespace(backbone='wavlm', use_raw=False, use_GAT=True, n_edges=10, use_aug=True, use_pool=True, use_clip=True))
clean_prob:
    value: 0.7
max_epochs:
    value: 7
n_edges:
    value: 10
reverb_prob:
    value: 0.3
reverb_t60:
    value:
        - 0.2
        - 0.35
        - 0.5
        - 0.7
        - 0.9
train_samples:
    value: 15000
