_wandb:
    value:
        cli_version: 0.24.0
        e:
            l8plqc12umzarn7er1k74ow5368jjkuv:
                codePath: algovirginia/workspace/DeepfakeDetectionRenewed/demo-Copy1.ipynb
                cpu_count: 30
                cpu_count_logical: 30
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1456701079552"
                        used: "38073729024"
                email: yashaspatil@gmail.com
                executable: /lambda/nfs/algovirginia/workspace/DeepfakeDetectionRenewed/venv/bin/python
                git:
                    commit: e98366503f2e8a9461a0ff5b37ba536b40839ba7
                    remote: https://github.com/Katluver44/DeepfakeDetectionRenewed.git
                gpu: NVIDIA A10
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 9216
                      memoryTotal: "24146608128"
                      name: NVIDIA A10
                      uuid: GPU-b2f19d70-f16d-1285-e70d-b2f398dc5ffa
                host: 157-151-164-83
                memory:
                    total: "238546341888"
                os: Linux-6.8.0-1046-nvidia-x86_64-with-glibc2.35
                program: algovirginia/workspace/DeepfakeDetectionRenewed/demo-Copy1.ipynb
                python: CPython 3.10.12
                root: .
                startedAt: "2026-03-06T02:45:16.099921Z"
                writerId: l8plqc12umzarn7er1k74ow5368jjkuv
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 103
            "3":
                - 2
                - 7
                - 13
                - 15
                - 66
            "4": 3.10.12
            "5": 0.24.0
            "6": 4.36.2
            "8":
                - 1
            "12": 0.24.0
            "13": linux-x86_64
args:
    value: null
cfg:
    value: Namespace(PhonemeGAT=Namespace(backbone='wavlm', use_raw=False, use_GAT=True, n_edges=1, use_aug=True, use_pool=True, use_clip=True))
