_wandb:
    value:
        cli_version: 0.24.0
        e:
            hlbrbma9ul5wi9cnix5ye1g684i8ruv3:
                codePath: algovirginia/workspace/DeepfakeDetectionRenewed/validation2_fixed.ipynb
                cpu_count: 30
                cpu_count_logical: 30
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1456701079552"
                        used: "26666668032"
                email: yashaspatil@gmail.com
                executable: /lambda/nfs/algovirginia/workspace/DeepfakeDetectionRenewed/venv/bin/python
                git:
                    commit: a79236f970777c481d787e9953bbcd6b83b1e755
                    remote: https://github.com/Katluver44/DeepfakeDetectionRenewed.git
                gpu: NVIDIA A10
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 9216
                      memoryTotal: "24146608128"
                      name: NVIDIA A10
                      uuid: GPU-acb092a5-a447-1801-c9a0-2eaf54c16ceb
                host: 150-136-216-186
                memory:
                    total: "238546358272"
                os: Linux-6.8.0-1046-nvidia-x86_64-with-glibc2.35
                program: algovirginia/workspace/DeepfakeDetectionRenewed/validation2_fixed.ipynb
                python: CPython 3.10.12
                root: /lambda/nfs/algovirginia/workspace/DeepfakeDetectionRenewed
                startedAt: "2026-04-02T04:29:13.067806Z"
                writerId: hlbrbma9ul5wi9cnix5ye1g684i8ruv3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 103
            "3":
                - 2
                - 13
                - 15
            "4": 3.10.12
            "5": 0.24.0
            "6": 4.36.2
            "8":
                - 1
            "10":
                - 20
            "12": 0.24.0
            "13": linux-x86_64
