_wandb:
    value:
        cli_version: 0.24.0
        e:
            rh4jzamp41qys23jzlr5vcjjnokeopv1:
                cpu_count: 30
                cpu_count_logical: 30
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "532608356352"
                        used: "29762011136"
                email: yashaspatil@gmail.com
                executable: /lambda/nfs/algovirginia/workspace/DeepfakeDetectionRenewed/venv/bin/python
                git:
                    commit: 8f873ee8073c26f57980f4d1a059afee72727c87
                    remote: https://github.com/Katluver44/DeepfakeDetectionRenewed.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-79710991-751a-0f82-23bb-8f87c9364ba2
                host: 132-145-136-207
                memory:
                    total: "232205713408"
                os: Linux-6.8.0-1040-nvidia-x86_64-with-glibc2.35
                program: <python with no main file>
                python: CPython 3.10.12
                root: /lambda/nfs/algovirginia/workspace/DeepfakeDetectionRenewed
                startedAt: "2026-01-24T02:11:16.845784Z"
                writerId: rh4jzamp41qys23jzlr5vcjjnokeopv1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
            "3":
                - 2
                - 16
            "4": 3.10.12
            "5": 0.24.0
            "6": 4.36.2
            "8":
                - 1
            "12": 0.24.0
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: dummy
epochs:
    value: 10
learning_rate:
    value: 0.02
test_run:
    value: true
