_wandb:
    value:
        cli_version: 0.24.0
        e:
            mepjluo1shogavdl700qpm3rzym7mr0a:
                codePath: algovirginia/workspace/DeepfakeDetectionRenewed/adv_demo_copy.ipynb
                cpu_count: 30
                cpu_count_logical: 30
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "532608356352"
                        used: "26556215296"
                email: yashaspatil@gmail.com
                executable: /lambda/nfs/algovirginia/workspace/DeepfakeDetectionRenewed/venv/bin/python
                git:
                    commit: a0bf7702f3eab1c16c6498c10fa28ce4cce3fd66
                    remote: https://github.com/Katluver44/DeepfakeDetectionRenewed.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-f46e6de8-5f92-375b-e931-b4815cc79886
                host: 150-136-33-217
                memory:
                    total: "232205611008"
                os: Linux-6.8.0-1046-nvidia-x86_64-with-glibc2.35
                program: algovirginia/workspace/DeepfakeDetectionRenewed/adv_demo_copy.ipynb
                python: CPython 3.10.12
                root: /lambda/nfs/algovirginia/workspace/DeepfakeDetectionRenewed
                startedAt: "2026-03-16T02:46:03.828719Z"
                writerId: mepjluo1shogavdl700qpm3rzym7mr0a
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
            "3":
                - 2
                - 16
            "4": 3.10.12
            "5": 0.24.0
            "6": 4.36.2
            "8":
                - 1
            "12": 0.24.0
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: dummy
epochs:
    value: 10
learning_rate:
    value: 0.02
test_run:
    value: true
